"""Runtime lifecycle, environment, and host execution abstractions."""

from app.runtime.command import (
    CommandExecutor,
    ExecutionEnvironmentError,
    HostShellExecutor,
    NativeLinuxBashExecutor,
    NativePowerShellExecutor,
    PowerShellExecutionProfile,
    WslBashExecutor,
    build_command_executor,
    build_linux_command_executor,
    resolve_command_environment,
)
from app.runtime.environment import EnvironmentContext, build_environment_context
from app.runtime.filesystem import FileSystemOperationError, NativeFileSystem, workspace_root_for
from app.runtime.workspace import WorkspaceManifest
from app.runtime.task_contracts import (
    ApprovalClass,
    ExecutionEvidence,
    ExecutionPolicy,
    NetworkPolicy,
    ResourceLimits,
    TaskKind,
    TaskPlan,
    TaskSpec,
    ToolchainProfile,
)
from app.runtime.task_resolver import (
    CallableTaskAdapter,
    ProjectTaskAdapter,
    TaskResolution,
    TaskResolver,
)
from app.runtime.execution_broker import (
    ExecutionBroker,
    LocalExecutionBroker,
    WorkerExecutionBroker,
    build_execution_broker,
)
from app.runtime.sandbox_worker import (
    ContainerCommandExecutor,
    ContainerWorker,
    SandboxWorker,
    WorkerCapabilities,
    WorkerStatus,
    WslWorker,
)

from app.runtime.agent_runtime import (
    AgentRuntime,
    AgentSession,
    SessionBusyError,
    active_count,
    cleanup_expired,
    finalize,
    get,
    get_or_create,
    release_run,
    runtime,
    try_claim_run,
)

__all__ = [
    "AgentRuntime",
    "AgentSession",
    "SessionBusyError",
    "active_count",
    "cleanup_expired",
    "finalize",
    "get",
    "get_or_create",
    "release_run",
    "runtime",
    "try_claim_run",
    "EnvironmentContext",
    "build_environment_context",
    "FileSystemOperationError",
    "NativeFileSystem",
    "workspace_root_for",
    "WorkspaceManifest",
    "ApprovalClass",
    "ExecutionEvidence",
    "ExecutionPolicy",
    "NetworkPolicy",
    "ResourceLimits",
    "TaskKind",
    "TaskPlan",
    "TaskSpec",
    "ToolchainProfile",
    "TaskResolution",
    "TaskResolver",
    "ProjectTaskAdapter",
    "CallableTaskAdapter",
    "ExecutionBroker",
    "LocalExecutionBroker",
    "WorkerExecutionBroker",
    "build_execution_broker",
    "SandboxWorker",
    "ContainerCommandExecutor",
    "ContainerWorker",
    "WorkerCapabilities",
    "WorkerStatus",
    "WslWorker",
    "ExecutionEnvironmentError",
    "CommandExecutor",
    "HostShellExecutor",
    "NativeLinuxBashExecutor",
    "NativePowerShellExecutor",
    "PowerShellExecutionProfile",
    "WslBashExecutor",
    "build_command_executor",
    "build_linux_command_executor",
    "resolve_command_environment",
]
