"""Runtime facts exposed to the Agent prompt.

The environment block is generated by the host runtime.  It is descriptive
context only; capability and risk policies remain enforced at tool boundaries.
"""

from __future__ import annotations

import os
import platform
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


@dataclass(frozen=True)
class EnvironmentContext:
    host_os: str
    execution_os: str
    shell: str
    execution_mode: str
    cwd: str
    workspace_roots: tuple[str, ...] = ()
    workspace_layout: tuple[tuple[str, str], ...] = ()
    path_style: str = "posix"
    executable_suffix: str = ""
    network_access: str = "restricted"
    filesystem_policy: str = "workspace-only"

    def to_prompt(self) -> str:
        lines = [
            "## Runtime environment (generated by the host runtime)",
            f"- Host OS: {self.host_os}",
            f"- Execution OS: {self.execution_os}",
            f"- Shell: {self.shell}",
            f"- Execution mode: {self.execution_mode}",
            f"- Working directory: {self.cwd}",
            f"- Path style: {self.path_style}",
            f"- Executable suffix: {self.executable_suffix or '(none)' }",
            f"- Network access: {self.network_access}",
            f"- Filesystem policy: {self.filesystem_policy}",
            "- Runtime facts are authoritative; do not invent another shell or workspace.",
            "- Use workspace-relative paths and the supplied cwd aliases whenever possible.",
        ]
        roots = []
        seen = set()
        current_key = _path_key(self.cwd)
        for root in self.workspace_roots:
            key = _path_key(root)
            if not key or key == current_key or key in seen:
                continue
            seen.add(key)
            roots.append(root)
        if roots:
            lines.append("- Workspace roots:")
            lines.extend(f"  - {root}" for root in roots)
        layout = []
        layout_seen = set()
        for name, root in self.workspace_layout:
            if not root:
                continue
            key = _path_key(root)
            if key in layout_seen:
                continue
            layout_seen.add(key)
            layout.append((name, root))
        if layout:
            lines.append("- Workspace layout:")
            lines.extend(f"  - {name}: {root}" for name, root in layout)
        return "\n".join(lines)


def _path_key(path: str) -> str:
    if not path:
        return ""
    return os.path.normcase(os.path.normpath(os.path.abspath(str(path))))


def build_environment_context(
    *,
    executor=None,
    cwd: str | None = None,
    workspace_roots: Iterable[str] = (),
    workspace_layout: Iterable[tuple[str, str]] = (),
    network_access: str = "restricted",
) -> EnvironmentContext:
    """Build a stable, prompt-safe description of the current execution target."""
    host_os = platform.system().lower() or os.name
    profile = getattr(executor, "profile", None)
    mode = str(getattr(profile, "name", "native"))

    if mode in {"linux-wsl", "wsl"}:
        execution_os, shell, path_style = "linux", "bash", "posix"
    elif mode in {"linux-native", "native-posix", "native_linux"}:
        execution_os, shell, path_style = "linux", "bash", "posix"
    elif mode in {"windows-powershell", "powershell"}:
        execution_os, shell, path_style = "windows", "powershell", "windows"
    else:
        execution_os = "windows" if os.name == "nt" else host_os
        shell = "powershell" if os.name == "nt" else "bash"
        path_style = "windows" if os.name == "nt" else "posix"

    roots = tuple(str(Path(root).resolve()) for root in workspace_roots if root)
    current = str(Path(cwd or os.getcwd()).resolve())
    return EnvironmentContext(
        host_os=host_os,
        execution_os=execution_os,
        shell=shell,
        execution_mode=mode,
        cwd=current,
        workspace_roots=roots,
        workspace_layout=tuple((str(name), str(root)) for name, root in workspace_layout if root),
        path_style=path_style,
        executable_suffix=".exe" if execution_os == "windows" else "",
        network_access=network_access,
    )


__all__ = ["EnvironmentContext", "build_environment_context"]
