/** UML data types – mirrors backend Pydantic models */

export enum Visibility {
  PUBLIC = '+',
  PRIVATE = '-',
  PROTECTED = '#',
}

export enum Stereotype {
  CLASS = 'class',
  INTERFACE = 'interface',
  ABSTRACT = 'abstract',
  ENUM = 'enum',
}

export enum RelationType {
  INHERITANCE = 'inheritance',
  COMPOSITION = 'composition',
  AGGREGATION = 'aggregation',
  ASSOCIATION = 'association',
  REALIZATION = 'realization',
  DEPENDENCY = 'dependency',
}

export interface UmlAttribute {
  name: string;
  type: string;
  visibility: Visibility;
  default_value?: string;
  is_static: boolean;
}

export interface UmlMethod {
  name: string;
  return_type: string;
  params: string;
  visibility: Visibility;
  is_static: boolean;
  is_abstract: boolean;
}

export interface Position {
  x: number;
  y: number;
}

export interface Size {
  width: number;
  height: number;
}

export interface UmlClass {
  id: string;
  name: string;
  stereotype: Stereotype;
  attributes: UmlAttribute[];
  methods: UmlMethod[];
  expanded_attributes?: boolean;
  expanded_methods?: boolean;
  position: Position;
  size: Size;
  note: string;
  provided_interfaces: string[];
  required_interfaces: string[];
}

export interface UmlRelation {
  id: string;
  source: string;
  target: string;
  type: RelationType;
  /** User-adjusted orthogonal routing points. Undefined means use auto-routing. */
  vertices?: Array<{ x: number; y: number }>;
  multiplicity_source: string;
  multiplicity_target: string;
  role_name: string;
  note: string;
}

import type { SeqLifeline, SeqMessage } from './sequence';
import type { CompNode, CompRelation } from './component';

export interface UmlDiagram {
  version: string;
  name: string;
  diagram_type?: string;  // "class" | "sequence" | "component"
  component_id?: string;  // CompNode.id — links this diagram to a component diagram node
  // Class diagram
  classes: UmlClass[];
  relations: UmlRelation[];
  // Sequence diagram
  lifelines?: SeqLifeline[];
  messages?: SeqMessage[];
  fragments?: import('./sequence').SeqFragment[];
  source_scopes?: import('./sequence').SeqSourceScope[];
  // Component diagram
  components?: CompNode[];
  comp_relations?: CompRelation[];
  // View
  grid_visible: boolean;
  grid_size: number;
  grid_color: string;
  grid_thickness: number;
  snap_to_grid: boolean;
  zoom: number;
  pan_x: number;
  pan_y: number;
}

export function createDefaultDiagram(name = 'Untitled'): UmlDiagram {
  return {
    version: '1.0',
    name,
    diagram_type: 'class',
    component_id: '',
    classes: [],
    relations: [],
    lifelines: [],
    messages: [],
    fragments: [],
    components: [],
    comp_relations: [],
    grid_visible: true,
    grid_size: 20,
    grid_color: '#f59e0b',
    grid_thickness: 1,
    snap_to_grid: true,
    zoom: 1.0,
    pan_x: 0,
    pan_y: 0,
  };
}

export function createDefaultClass(position?: Position): UmlClass {
  return {
    id: `class_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
    name: 'NewClass',
    stereotype: Stereotype.CLASS,
    attributes: [],
    methods: [],
    expanded_attributes: false,
    expanded_methods: false,
    position: position || { x: 100, y: 100 },
    size: { width: 200, height: 150 },
    note: '',
    provided_interfaces: [],
    required_interfaces: [],
  };
}

export function createDefaultRelation(source: string, target: string): UmlRelation {
  return {
    id: `rel_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
    source,
    target,
    type: RelationType.ASSOCIATION,
    multiplicity_source: '',
    multiplicity_target: '',
    role_name: '',
    note: '',
  };
}

// ── Project (multi-diagram container) ─────────────────

export interface Project {
  version: string;
  /** Monotonic server-side revision used for optimistic saves. */
  revision?: number;
  name: string;
  grid_settings: GridSettings;
  diagrams: UmlDiagram[];
  active_diagram_index: number;
}

export interface GridSettings {
  grid_visible: boolean;
  grid_size: number;
  grid_color: string;
  grid_thickness: number;
  snap_to_grid: boolean;
}

export const DEFAULT_GRID_SETTINGS: GridSettings = {
  grid_visible: true,
  grid_size: 20,
  grid_color: '#f59e0b',
  grid_thickness: 1,
  snap_to_grid: true,
};

export function createDefaultProject(name = 'Untitled'): Project {
  return {
    version: '1.0',
    revision: 0,
    name,
    grid_settings: { ...DEFAULT_GRID_SETTINGS },
    diagrams: [],
    active_diagram_index: 0,
  };
}

// ── Global optimization result types ─────────────────

/** A single diagram generated by the LLM in a global optimization result. */
export interface GeneratedDiagram {
  type: string;        // "class" | "sequence" | "component"
  name: string;
  component_id: string;
  data: Record<string, unknown>;  // full diagram fields
}
